// src/components/Proyectos/Proyectos.tsx
import { useNavigate } from 'react-router-dom'
import { projects } from '../../data/projects.data'
import type { Project } from '../../models/project.model'
import s from './Proyectos.module.sass'

export function Proyectos() {
  const navigate = useNavigate()

  function abrirProyecto(project: Project) {
    if (project.id === 1) return
    navigate('/proyecto-no-disponible')
  }

  return (
    <section id="proyectos" className={s['proyectos-section']}>
      <div className={s.container}>
        <div className={s['section-header']}>
          <h2 className={s['section-title']}>Mis Proyectos</h2>
          <p className={s['section-subtitle']}>Explora mi trabajo y las tecnologías que he utilizado</p>
        </div>

        <div className={s['projects-grid']}>
          {projects.map((project) => (
            <div
              key={project.id}
              className={s['project-card']}
              onClick={() => abrirProyecto(project)}
            >
              <div className={s['project-icon']}>
                <img src={project.icon} alt={project.name} />
              </div>
              <div className={s['project-info']}>
                <h3 className={s['project-title']}>{project.name}</h3>
                <p className={s['project-description']}>{project.description}</p>
                <div className={s['project-tech']}>
                  {project.technologies.map((tech) => (
                    <span key={tech} className={s['tech-tag']}>{tech}</span>
                  ))}
                </div>
              </div>
              <div className={s['project-overlay']}>
                <span className={s['ver-proyecto']}>
                  {project.id === 1 ? 'Este proyecto' : 'Ver Proyecto'}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

// wb-curriculum/src/app/proyectos/proyectos.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

interface Proyecto {
  id: number;
  nombre: string;
  descripcion: string;
  icono: string;
  tecnologias: string[];
  url: string;
}

@Component({
  selector: 'proyectos',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './proyectos.component.html',
  styleUrl: './proyectos.component.sass'
})
export class Proyectos {
  private router = inject(Router);

  proyectos: Proyecto[] = [
    {
      id: 1,
      nombre: "Portfolio Personal",
      descripcion: "Portfolio de mi trayectoria profesional completa, abarcando tanto mi experiencia laboral como mis proyectos personales",
      icono: "programmer_icon.svg",
      tecnologias: ["Angular", "Antigravity", "SASS", "TypeScript"],
      url: "#"
    },
    {
      id: 2,
      nombre: "E-commerce Platform",
      descripcion: "Plataforma completa de comercio electrónico con gestión de productos, usuarios y pagos",
      icono: "https://cdn-icons-png.flaticon.com/512/3081/3081559.png",
      tecnologias: ["Angular", "Node.js", "MongoDB", "Stripe"],
      url: "https://github.com/tu-usuario/ecommerce"
    },
    {
      id: 3,
      nombre: "Task Manager App",
      descripcion: "Aplicación de gestión de tareas con interfaz intuitiva y funcionalidades avanzadas",
      icono: "https://cdn-icons-png.flaticon.com/512/1827/1827933.png",
      tecnologias: ["React", "TypeScript", "Firebase"],
      url: "https://github.com/tu-usuario/task-manager"
    },
    {
      id: 4,
      nombre: "Weather Dashboard",
      descripcion: "Dashboard meteorológico con datos en tiempo real y gráficos interactivos",
      icono: "https://cdn-icons-png.flaticon.com/512/3222/3222800.png",
      tecnologias: ["Vue.js", "Chart.js", "OpenWeather API"],
      url: "https://github.com/tu-usuario/weather-dashboard"
    }
  ];

  abrirProyecto(proyecto: Proyecto): void {
    if (proyecto.id === 1) return;

    // Redirige a la pantalla 404 del sitio para los proyectos de ejemplo
    this.router.navigate(['/proyecto-no-disponible']);
  }
}

<section id="proyectos" class="proyectos-section">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title">Mis Proyectos</h2>
      <p class="section-subtitle">Explora mi trabajo y las tecnologías que he utilizado</p>
    </div>

    <div class="projects-grid">
      <div class="project-card" *ngFor="let proyecto of proyectos" (click)="abrirProyecto(proyecto)">
        <div class="project-icon">
          <img [src]="proyecto.icono" [alt]="proyecto.nombre" />
        </div>
        <div class="project-info">
          <h3 class="project-title">{{ proyecto.nombre }}</h3>
          <p class="project-description">{{ proyecto.descripcion }}</p>
          <div class="project-tech">
            <span class="tech-tag" *ngFor="let tech of proyecto.tecnologias">{{ tech }}</span>
          </div>
        </div>
        <div class="project-overlay">
          <span class="ver-proyecto">{{ proyecto.id === 1 ? 'Este proyecto' : 'Ver Proyecto' }}</span>
        </div>
      </div>
    </div>
  </div>
</section>
